### ISSUE TITLE
Puppetlabs-stdlib version range is too restrictive

### ISSUE THREAD

**Issue by madAndroid** [dhollinger/autofs-puppet#21] opened 2016-11-03 14:45 UTC
Hi,

Firstly, thank you for a great module.
We've got a problem however, in that a few dependencies we use require `stdlib` > `4.13.0` ... and since this module is pinned to a version <= `4.12.0`, we're seeing failed dependency resolution when running librarian-puppet - is there any particular reason that you've pinned to that stdlib release? If it's because of the deprecation warnings, we're seeing the same ... but it's preferable to have the deprecation warnings, and still be able to manage our dependencies cleanly.
Would you consider a pull-request that expands the dependency range?

Thanks in advance

**Comment by dhollinger** [comment] 2016-11-07 04:30
I would definitely consider a pull request that would extend the dependency range. I have it as strict as it is right now primarily due to the fact that I haven't had time (or an environment) to ensure that the module still works with older versions of stdlib. Same restrictions with concat.

I am open to extending those as far as possible, as long as it is tested.

**Comment by dhollinger** [comment] 2016-11-07 04:42
Correction, I misread part of what you were saying. I will get some tests in and set the range to encompass up to 4.13.1 at least.

**Comment by dhollinger** [comment] 2016-11-07 06:31
Updated to include relevant versions of puppetlabs-stdlib in commit https://github.com/dhollinger/autofs-puppet/commit/597002a4596413e8512fce161b27e53245f96b6d, I will deploy the new version to the Forge tomorrow afternoon.

I will update the ticket once the release has been deployed so that you can validate that the issue is fixed.

**Comment by madAndroid** [comment] 2016-11-07 12:15
Thanks for looking into this :) Suggestion: given that puppetlabs follow semver for stdlib, would it not be better to specify a version range of `>= 3.2.0 < 5.0.0` ? that would mean that any new features in the `4.x.x` versions would be acceptable, and only breaking changes would be avoided?

**Comment by dhollinger** [comment] 2016-11-07 20:03
Had to think about that for a bit as my SysAdmin brain is screaming to not do that in case a minor or patch release breaks something. That said, I'm going to go ahead and set the range to `>= 3.2.0 < 5.0.0`.

Applying similar range to puppetlabs-concat: `>= 2.0.0 < 3.0.0`

**Comment by dhollinger** [comment] 2016-11-07 20:23
Version 1.4.4 released. Closing this issue, please reopen if you continue to encounter the issue

**Closed as completed by dhollinger** 2016-11-07 20:23 UTC
Labels: enhancement, v1.4.4

**Comment by madAndroid** [comment] 2016-11-07 21:03
Thanks! :)
